### ISSUE TITLE
Branch build of feature/[...]#86 of kivakit fails

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/telenav-build#2] opened 2022-07-27 14:13 UTC
Not sure how this is possible. It's is particularly puzzling because the string "1.5.16" does not appear anywhere.
```
Error:  Plugin com.telenav.cactus:cactus-maven-plugin:1.5.16 or one of its dependencies could not be resolved: Could not find artifact com.telenav.cactus:cactus-maven-plugin:jar:1.5.16 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[374](https://github.com/Telenav/kivakit/runs/7531289165?check_suite_focus=true#step:24:375)
```

**Comment by timboudreau** [comment] 2022-07-27 22:39
No idea.  What were you doing when you encountered this?

**Comment by timboudreau** [comment] 2022-07-27 22:57
The problem is that the clone command in `build-branch.yml` should pass `-b develop` or similar - otherwise it tries to build things against release/current.  Probably something in there references cactus 1.5.16.

**Comment by timboudreau** [comment] 2022-07-27 23:25
Okay, fixed in all `build-branch.yml` files.  The build is now failing for other reasons (java code, not build issues).

**Closed as completed by timboudreau** 2022-07-27 23:25 UTC
Labels: bug
